/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <pricingengines/credit/integralcdsengine.hpp>
#include <pricingengines/credit/isdacdsengine.hpp>
#include <pricingengines/credit/midpointcdsengine.hpp>

