/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <instruments/bonds/amortizingcmsratebond.hpp>
#include <instruments/bonds/amortizingfixedratebond.hpp>
#include <instruments/bonds/amortizingfloatingratebond.hpp>
#include <instruments/bonds/btp.hpp>
#include <instruments/bonds/cmsratebond.hpp>
#include <instruments/bonds/convertiblebonds.hpp>
#include <instruments/bonds/cpibond.hpp>
#include <instruments/bonds/fixedratebond.hpp>
#include <instruments/bonds/floatingratebond.hpp>
#include <instruments/bonds/zerocouponbond.hpp>

