/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <models/marketmodels/products/pathwise/pathwiseproductcallspecified.hpp>
#include <models/marketmodels/products/pathwise/pathwiseproductcaplet.hpp>
#include <models/marketmodels/products/pathwise/pathwiseproductcashrebate.hpp>
#include <models/marketmodels/products/pathwise/pathwiseproductinversefloater.hpp>
#include <models/marketmodels/products/pathwise/pathwiseproductswap.hpp>
#include <models/marketmodels/products/pathwise/pathwiseproductswaption.hpp>

