/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <models/marketmodels/products/multistep/callspecifiedmultiproduct.hpp>
#include <models/marketmodels/products/multistep/cashrebate.hpp>
#include <models/marketmodels/products/multistep/exerciseadapter.hpp>
#include <models/marketmodels/products/multistep/multistepcoinitialswaps.hpp>
#include <models/marketmodels/products/multistep/multistepcoterminalswaps.hpp>
#include <models/marketmodels/products/multistep/multistepcoterminalswaptions.hpp>
#include <models/marketmodels/products/multistep/multistepforwards.hpp>
#include <models/marketmodels/products/multistep/multistepinversefloater.hpp>
#include <models/marketmodels/products/multistep/multistepnothing.hpp>
#include <models/marketmodels/products/multistep/multistepoptionlets.hpp>
#include <models/marketmodels/products/multistep/multisteppathwisewrapper.hpp>
#include <models/marketmodels/products/multistep/multistepperiodcapletswaptions.hpp>
#include <models/marketmodels/products/multistep/multistepratchet.hpp>
#include <models/marketmodels/products/multistep/multistepswap.hpp>
#include <models/marketmodels/products/multistep/multistepswaption.hpp>
#include <models/marketmodels/products/multistep/multisteptarn.hpp>

