/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <models/volatility/constantestimator.hpp>
#include <models/volatility/simplelocalestimator.hpp>
#include <models/volatility/garmanklass.hpp>
#include <models/volatility/garch.hpp>

