/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <indexes/inflation/aucpi.hpp>
#include <indexes/inflation/euhicp.hpp>
#include <indexes/inflation/frhicp.hpp>
#include <indexes/inflation/ukhicp.hpp>
#include <indexes/inflation/ukrpi.hpp>
#include <indexes/inflation/uscpi.hpp>
#include <indexes/inflation/zacpi.hpp>

