/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <experimental/models/normalclvmodel.hpp>
#include <experimental/models/squarerootclvmodel.hpp>

