/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <currencies/africa.hpp>
#include <currencies/america.hpp>
#include <currencies/asia.hpp>
#include <currencies/crypto.hpp>
#include <currencies/europe.hpp>
#include <currencies/exchangeratemanager.hpp>
#include <currencies/oceania.hpp>

