/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <termstructures/inflation/inflationhelpers.hpp>
#include <termstructures/inflation/inflationtraits.hpp>
#include <termstructures/inflation/interpolatedyoyinflationcurve.hpp>
#include <termstructures/inflation/interpolatedzeroinflationcurve.hpp>
#include <termstructures/inflation/piecewiseyoyinflationcurve.hpp>
#include <termstructures/inflation/piecewisezeroinflationcurve.hpp>
#include <termstructures/inflation/seasonality.hpp>

