/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <math/solvers1d/bisection.hpp>
#include <math/solvers1d/brent.hpp>
#include <math/solvers1d/falseposition.hpp>
#include <math/solvers1d/finitedifferencenewtonsafe.hpp>
#include <math/solvers1d/halley.hpp>
#include <math/solvers1d/newton.hpp>
#include <math/solvers1d/newtonsafe.hpp>
#include <math/solvers1d/ridder.hpp>
#include <math/solvers1d/secant.hpp>

