/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <pricingengines/basket/bjerksundstenslandspreadengine.hpp>
#include <pricingengines/basket/choibasketengine.hpp>
#include <pricingengines/basket/denglizhoubasketengine.hpp>
#include <pricingengines/basket/fd2dblackscholesvanillaengine.hpp>
#include <pricingengines/basket/fdndimblackscholesvanillaengine.hpp>
#include <pricingengines/basket/kirkengine.hpp>
#include <pricingengines/basket/mcamericanbasketengine.hpp>
#include <pricingengines/basket/mceuropeanbasketengine.hpp>
#include <pricingengines/basket/operatorsplittingspreadengine.hpp>
#include <pricingengines/basket/singlefactorbsmbasketengine.hpp>
#include <pricingengines/basket/spreadblackscholesvanillaengine.hpp>
#include <pricingengines/basket/stulzengine.hpp>
#include <pricingengines/basket/vectorbsmprocessextractor.hpp>

