/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <indexes/swap/chfliborswap.hpp>
#include <indexes/swap/euriborswap.hpp>
#include <indexes/swap/eurliborswap.hpp>
#include <indexes/swap/gbpliborswap.hpp>
#include <indexes/swap/jpyliborswap.hpp>
#include <indexes/swap/usdliborswap.hpp>

