/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <experimental/termstructures/basisswapratehelpers.hpp>
#include <experimental/termstructures/crosscurrencyratehelpers.hpp>

