/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <math/abcdmathfunction.hpp>
#include <math/array.hpp>
#include <math/autocovariance.hpp>
#include <math/bernsteinpolynomial.hpp>
#include <math/beta.hpp>
#include <math/bspline.hpp>
#include <math/comparison.hpp>
#include <math/errorfunction.hpp>
#include <math/expm1.hpp>
#include <math/factorial.hpp>
#include <math/fastfouriertransform.hpp>
#include <math/functional.hpp>
#include <math/generallinearleastsquares.hpp>
#include <math/kernelfunctions.hpp>
#include <math/incompletegamma.hpp>
#include <math/interpolation.hpp>
#include <math/linearleastsquaresregression.hpp>
#include <math/matrix.hpp>
#include <math/modifiedbessel.hpp>
#include <math/pascaltriangle.hpp>
#include <math/polynomialmathfunction.hpp>
#include <math/primenumbers.hpp>
#include <math/quadratic.hpp>
#include <math/rounding.hpp>
#include <math/richardsonextrapolation.hpp>
#include <math/solver1d.hpp>
#include <math/transformedgrid.hpp>

#include <math/copulas/all.hpp>
#include <math/distributions/all.hpp>
#include <math/integrals/all.hpp>
#include <math/interpolations/all.hpp>
#include <math/matrixutilities/all.hpp>
#include <math/ode/all.hpp>
#include <math/optimization/all.hpp>
#include <math/randomnumbers/all.hpp>
#include <math/solvers1d/all.hpp>
#include <math/statistics/all.hpp>
