/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <math/copulas/alimikhailhaqcopula.hpp>
#include <math/copulas/claytoncopula.hpp>
#include <math/copulas/farliegumbelmorgensterncopula.hpp>
#include <math/copulas/frankcopula.hpp>
#include <math/copulas/galamboscopula.hpp>
#include <math/copulas/gaussiancopula.hpp>
#include <math/copulas/gumbelcopula.hpp>
#include <math/copulas/huslerreisscopula.hpp>
#include <math/copulas/independentcopula.hpp>
#include <math/copulas/marshallolkincopula.hpp>
#include <math/copulas/maxcopula.hpp>
#include <math/copulas/mincopula.hpp>
#include <math/copulas/plackettcopula.hpp>

