/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <time/daycounters/actual360.hpp>
#include <time/daycounters/actual364.hpp>
#include <time/daycounters/actual365fixed.hpp>
#include <time/daycounters/actual36525.hpp>
#include <time/daycounters/actual366.hpp>
#include <time/daycounters/actualactual.hpp>
#include <time/daycounters/business252.hpp>
#include <time/daycounters/one.hpp>
#include <time/daycounters/simpledaycounter.hpp>
#include <time/daycounters/thirty360.hpp>
#include <time/daycounters/thirty365.hpp>
#include <time/daycounters/yearfractiontodate.hpp>

