/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <pricingengines/exotic/analyticamericanmargrabeengine.hpp>
#include <pricingengines/exotic/analyticcomplexchooserengine.hpp>
#include <pricingengines/exotic/analyticcompoundoptionengine.hpp>
#include <pricingengines/exotic/analyticeuropeanmargrabeengine.hpp>
#include <pricingengines/exotic/analyticsimplechooserengine.hpp>

