/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <pricingengines/vanilla/analyticbsmhullwhiteengine.hpp>
#include <pricingengines/vanilla/analyticdigitalamericanengine.hpp>
#include <pricingengines/vanilla/analyticdividendeuropeanengine.hpp>
#include <pricingengines/vanilla/analyticeuropeanengine.hpp>
#include <pricingengines/vanilla/analyticeuropeanvasicekengine.hpp>
#include <pricingengines/vanilla/analyticcevengine.hpp>
#include <pricingengines/vanilla/analyticgjrgarchengine.hpp>
#include <pricingengines/vanilla/analytich1hwengine.hpp>
#include <pricingengines/vanilla/analytichestonengine.hpp>
#include <pricingengines/vanilla/analytichestonhullwhiteengine.hpp>
#include <pricingengines/vanilla/analyticptdhestonengine.hpp>
#include <pricingengines/vanilla/baroneadesiwhaleyengine.hpp>
#include <pricingengines/vanilla/batesengine.hpp>
#include <pricingengines/vanilla/binomialengine.hpp>
#include <pricingengines/vanilla/bjerksundstenslandengine.hpp>
#include <pricingengines/vanilla/coshestonengine.hpp>
#include <pricingengines/vanilla/discretizedvanillaoption.hpp>
#include <pricingengines/vanilla/exponentialfittinghestonengine.hpp>
#include <pricingengines/vanilla/hestonexpansionengine.hpp>
#include <pricingengines/vanilla/integralengine.hpp>
#include <pricingengines/vanilla/jumpdiffusionengine.hpp>
#include <pricingengines/vanilla/juquadraticengine.hpp>
#include <pricingengines/vanilla/fdbatesvanillaengine.hpp>
#include <pricingengines/vanilla/fdblackscholesvanillaengine.hpp>
#include <pricingengines/vanilla/fdblackscholesshoutengine.hpp>
#include <pricingengines/vanilla/fdcevvanillaengine.hpp>
#include <pricingengines/vanilla/fdhestonhullwhitevanillaengine.hpp>
#include <pricingengines/vanilla/fdhestonvanillaengine.hpp>
#include <pricingengines/vanilla/fdcirvanillaengine.hpp>
#include <pricingengines/vanilla/fdsabrvanillaengine.hpp>
#include <pricingengines/vanilla/fdsimplebsswingengine.hpp>
#include <pricingengines/vanilla/mcamericanengine.hpp>
#include <pricingengines/vanilla/mcdigitalengine.hpp>
#include <pricingengines/vanilla/mceuropeanengine.hpp>
#include <pricingengines/vanilla/mceuropeanhestonengine.hpp>
#include <pricingengines/vanilla/mceuropeangjrgarchengine.hpp>
#include <pricingengines/vanilla/mchestonhullwhiteengine.hpp>
#include <pricingengines/vanilla/mcvanillaengine.hpp>
#include <pricingengines/vanilla/qdfpamericanengine.hpp>
#include <pricingengines/vanilla/qdplusamericanengine.hpp>

