/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <indexes/bmaindex.hpp>
#include <indexes/equityindex.hpp>
#include <indexes/iborindex.hpp>
#include <indexes/indexmanager.hpp>
#include <indexes/inflationindex.hpp>
#include <indexes/interestrateindex.hpp>
#include <indexes/region.hpp>
#include <indexes/swapindex.hpp>

#include <indexes/ibor/all.hpp>
#include <indexes/inflation/all.hpp>
#include <indexes/swap/all.hpp>
