/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <math/optimization/armijo.hpp>
#include <math/optimization/bfgs.hpp>
#include <math/optimization/conjugategradient.hpp>
#include <math/optimization/constraint.hpp>
#include <math/optimization/costfunction.hpp>
#include <math/optimization/differentialevolution.hpp>
#include <math/optimization/endcriteria.hpp>
#include <math/optimization/goldstein.hpp>
#include <math/optimization/leastsquare.hpp>
#include <math/optimization/levenbergmarquardt.hpp>
#include <math/optimization/linesearch.hpp>
#include <math/optimization/linesearchbasedmethod.hpp>
#include <math/optimization/lmdif.hpp>
#include <math/optimization/method.hpp>
#include <math/optimization/problem.hpp>
#include <math/optimization/projectedconstraint.hpp>
#include <math/optimization/projectedcostfunction.hpp>
#include <math/optimization/projection.hpp>
#include <math/optimization/simplex.hpp>
#include <math/optimization/simulatedannealing.hpp>
#include <math/optimization/spherecylinder.hpp>
#include <math/optimization/steepestdescent.hpp>

