/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <quotes/compositequote.hpp>
#include <quotes/derivedquote.hpp>
#include <quotes/eurodollarfuturesquote.hpp>
#include <quotes/forwardswapquote.hpp>
#include <quotes/forwardvaluequote.hpp>
#include <quotes/futuresconvadjustmentquote.hpp>
#include <quotes/impliedstddevquote.hpp>
#include <quotes/lastfixingquote.hpp>
#include <quotes/simplequote.hpp>

