/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <math/interpolations/abcdinterpolation.hpp>
#include <math/interpolations/backwardflatinterpolation.hpp>
#include <math/interpolations/backwardflatlinearinterpolation.hpp>
#include <math/interpolations/bicubicsplineinterpolation.hpp>
#include <math/interpolations/bilinearinterpolation.hpp>
#include <math/interpolations/chebyshevinterpolation.hpp>
#include <math/interpolations/convexmonotoneinterpolation.hpp>
#include <math/interpolations/cubicinterpolation.hpp>
#include <math/interpolations/extrapolation.hpp>
#include <math/interpolations/flatextrapolation2d.hpp>
#include <math/interpolations/forwardflatinterpolation.hpp>
#include <math/interpolations/interpolation2d.hpp>
#include <math/interpolations/kernelinterpolation.hpp>
#include <math/interpolations/kernelinterpolation2d.hpp>
#include <math/interpolations/lagrangeinterpolation.hpp>
#include <math/interpolations/linearinterpolation.hpp>
#include <math/interpolations/loginterpolation.hpp>
#include <math/interpolations/mixedinterpolation.hpp>
#include <math/interpolations/multicubicspline.hpp>
#include <math/interpolations/sabrinterpolation.hpp>
#include <math/interpolations/xabrinterpolation.hpp>

