/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <termstructures/volatility/inflation/constantcpivolatility.hpp>
#include <termstructures/volatility/inflation/cpivolatilitystructure.hpp>
#include <termstructures/volatility/inflation/yoyinflationoptionletvolatilitystructure.hpp>

