/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <patterns/curiouslyrecurring.hpp>
#include <patterns/lazyobject.hpp>
#include <patterns/observable.hpp>
#include <patterns/singleton.hpp>
#include <patterns/visitor.hpp>

