/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <processes/batesprocess.hpp>
#include <processes/blackscholesprocess.hpp>
#include <processes/coxingersollrossprocess.hpp>
#include <processes/endeulerdiscretization.hpp>
#include <processes/eulerdiscretization.hpp>
#include <processes/forwardmeasureprocess.hpp>
#include <processes/g2process.hpp>
#include <processes/geometricbrownianprocess.hpp>
#include <processes/gjrgarchprocess.hpp>
#include <processes/gsrprocess.hpp>
#include <processes/gsrprocesscore.hpp>
#include <processes/hestonprocess.hpp>
#include <processes/hestonslvprocess.hpp>
#include <processes/hullwhiteprocess.hpp>
#include <processes/hybridhestonhullwhiteprocess.hpp>
#include <processes/jointstochasticprocess.hpp>
#include <processes/merton76process.hpp>
#include <processes/mfstateprocess.hpp>
#include <processes/ornsteinuhlenbeckprocess.hpp>
#include <processes/squarerootprocess.hpp>
#include <processes/stochasticprocessarray.hpp>

