/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <cashflows/averagebmacoupon.hpp>
#include <cashflows/capflooredcoupon.hpp>
#include <cashflows/capflooredinflationcoupon.hpp>
#include <cashflows/cashflows.hpp>
#include <cashflows/cashflowvectors.hpp>
#include <cashflows/cmscoupon.hpp>
#include <cashflows/conundrumpricer.hpp>
#include <cashflows/coupon.hpp>
#include <cashflows/couponpricer.hpp>
#include <cashflows/cpicoupon.hpp>
#include <cashflows/cpicouponpricer.hpp>
#include <cashflows/digitalcmscoupon.hpp>
#include <cashflows/digitalcoupon.hpp>
#include <cashflows/digitaliborcoupon.hpp>
#include <cashflows/dividend.hpp>
#include <cashflows/duration.hpp>
#include <cashflows/equitycashflow.hpp>
#include <cashflows/fixedratecoupon.hpp>
#include <cashflows/floatingratecoupon.hpp>
#include <cashflows/iborcoupon.hpp>
#include <cashflows/indexedcashflow.hpp>
#include <cashflows/inflationcoupon.hpp>
#include <cashflows/inflationcouponpricer.hpp>
#include <cashflows/lineartsrpricer.hpp>
#include <cashflows/multipleresetscoupon.hpp>
#include <cashflows/overnightindexedcoupon.hpp>
#include <cashflows/overnightindexedcouponpricer.hpp>
#include <cashflows/rangeaccrual.hpp>
#include <cashflows/rateaveraging.hpp>
#include <cashflows/replication.hpp>
#include <cashflows/simplecashflow.hpp>
#include <cashflows/timebasket.hpp>
#include <cashflows/yoyinflationcoupon.hpp>
#include <cashflows/zeroinflationcashflow.hpp>

