/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <math/statistics/convergencestatistics.hpp>
#include <math/statistics/discrepancystatistics.hpp>
#include <math/statistics/gaussianstatistics.hpp>
#include <math/statistics/generalstatistics.hpp>
#include <math/statistics/histogram.hpp>
#include <math/statistics/incrementalstatistics.hpp>
#include <math/statistics/riskstatistics.hpp>
#include <math/statistics/sequencestatistics.hpp>
#include <math/statistics/statistics.hpp>

