/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <experimental/varianceoption/integralhestonvarianceoptionengine.hpp>
#include <experimental/varianceoption/varianceoption.hpp>

