/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <pricingengines/cliquet/analyticcliquetengine.hpp>
#include <pricingengines/cliquet/analyticperformanceengine.hpp>
#include <pricingengines/cliquet/mcperformanceengine.hpp>

