/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <experimental/coupons/cmsspreadcoupon.hpp>
#include <experimental/coupons/digitalcmsspreadcoupon.hpp>
#include <experimental/coupons/lognormalcmsspreadpricer.hpp>
#include <experimental/coupons/proxyibor.hpp>
#include <experimental/coupons/quantocouponpricer.hpp>
#include <experimental/coupons/strippedcapflooredcoupon.hpp>
#include <experimental/coupons/swapspreadindex.hpp>

